export const categoryOptions = [
  { key: 'piano', value: 'Piano' },
  { key: 'guitare', value: 'Guitare' },
  { key: 'violon', value: 'Violon' },
  { key: 'batterie', value: 'Batterie' },
  { key: 'basse', value: 'Basse' },
  { key: 'saxophone', value: 'Saxophone' },
  { key: 'flute', value: 'Flûte' },
  { key: 'trompette', value: 'Trompette' },
  { key: 'violoncelle', value: 'Violoncelle' },
  { key: 'ukulele', value: 'Ukulélé' },
  { key: 'chant', value: 'Chant' },
  { key: 'chorale', value: 'Chorale' },
  { key: 'solfege', value: 'Solfège' },
  { key: 'clarinette', value: 'Clarinette' },
  { key: 'trombone', value: 'Trombone' },
  { key: 'hautbois', value: 'Hautbois' },
  { key: 'harpe', value: 'Harpe' },
  { key: 'accordeon', value: 'Accordéon' },
  { key: 'banjo', value: 'Banjo' },
  { key: 'mandoline', value: 'Mandoline' },
  { key: 'percussions', value: 'Percussions' },
  { key: 'dj', value: 'DJ' },
  { key: 'production musicale', value: 'Production musicale' },
  { key: 'autre', value: 'Autre' },
] as const;

export const levelOptions = [
  { key: 'debutant', value: 'Débutant' },
  { key: 'intermediaire', value: 'Intermédiaire' },
  { key: 'avance', value: 'Avancé' },
] as const;
