export const categoryOptions = [
  { key: 'piano', value: 'Piano' },
  { key: 'guitare', value: 'Guitare' },
  { key: 'violon', value: 'Violon' },
  { key: 'batterie', value: 'Batterie' },
  { key: 'basse', value: 'Basse' },
  { key: 'saxophone', value: 'Saxophone' },
  { key: 'flute', value: 'Flûte' },
  { key: 'trompette', value: 'Trompette' },
  { key: 'violoncelle', value: 'Violoncelle' },
  { key: 'ukulele', value: 'Ukulélé' },
  { key: 'chant', value: 'Chant' },
  { key: 'chorale', value: 'Chorale' },
  { key: 'solfege', value: 'Solfège' },
  { key: 'clarinette', value: 'Clarinette' },
  { key: 'trombone', value: 'Trombone' },
  { key: 'hautbois', value: 'Hautbois' },
  { key: 'harpe', value: 'Harpe' },
  { key: 'accordeon', value: 'Accordéon' },
  { key: 'banjo', value: 'Banjo' },
  { key: 'mandoline', value: 'Mandoline' },
  { key: 'percussions', value: 'Percussions' },
  { key: 'dj', value: 'DJ' },
  { key: 'production-musicale', value: 'Production musicale' },
  { key: 'autre', value: 'Autre' },
] as const;

export const levelOptions = [
  { key: 'debutant', value: 'Débutant' },
  { key: 'intermediaire', value: 'Intermédiaire' },
  { key: 'avance', value: 'Avancé' },
] as const;

export const TIME_SLOTS = [
  '09:00',
  '09:30',
  '10:00',
  '10:30',
  '11:00',
  '11:30',
  '12:00',
  '12:30',
  '13:00',
  '13:30',
  '14:00',
  '14:30',
  '15:00',
  '15:30',
  '16:00',
  '16:30',
  '17:00',
  '17:30',
  '18:00',
  '18:30',
  '19:00',
  '19:30',
  '20:00',
  '20:30',
  '21:00',
  '21:30',
  '22:00',
  '22:30',
] as const;

export type TimeSlot = (typeof TIME_SLOTS)[number];
